sudo: false
dist: trusty
cache: 
  apt: true
  directories:
    - $HOME/.deps
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: QF_ARCH=OSX
      language: c++
      compiler: clang
    - os: linux
      language: c++
      compiler: gcc-4.9
      env: QF_ARCH=x86
      addons:
        apt:
          sources:
            - kubuntu-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - build-essential
            - gcc-4.9-multilib
            - g++-4.9-multilib
            - gcc-multilib
            - libgnutls-dev:i386
            - libidn11-dev:i386
            - libkrb5-dev:i386
            - librtmp-dev:i386
            - libpng-dev:i386
            - libgl1-mesa-dev:i386
            - libglu1-mesa-dev:i386
            - libpulse-dev:i386
            - libsdl2-dev:i386
            - libopenal-dev:i386
            - libvorbis-dev:i386
            - libtheora-dev:i386
            - libfreetype6-dev:i386
            - zlib1g-dev:i386
            - libcurl4-gnutls-dev:i386
            - libglib2.0-dev:i386
    - os: linux
      language: c++
      compiler: clang
      env: QF_ARCH=x86_64
      addons:
        apt:
          packages:
            - clang
            - cmake
            - build-essential
            - libsdl2-dev
            - libopenal-dev
            - libvorbis-dev
            - libtheora-dev
            - libfreetype6-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev


install:
  - if [[ "$QF_ARCH" == "x86_64" ]]; then export CC=clang CXX=clang++; fi
  - if [[ "$QF_ARCH" == "x86" ]]; then export CC=gcc-4.9 CXX=g++-4.9; fi
  - cd "$TRAVIS_BUILD_DIR/source"
  - if [[ "$QF_ARCH" == "x86_64" ]]; then cmake .; fi
  - if [[ "$QF_ARCH" == "x86" ]]; then cmake -DCMAKE_TOOLCHAIN_FILE=cmake/i386-linux-gnu.cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 .; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then cmake -G Xcode .; fi
  - cd "$TRAVIS_BUILD_DIR"

script:
  - curl https://warfork.com/downloads/sdk/ --output "$TRAVIS_BUILD_DIR/third-party/steamworks/sdk.zip"
  - unzip "$TRAVIS_BUILD_DIR/third-party/steamworks/sdk.zip"
  - cd source
  - if [[ "$QF_ARCH" == "x86_64" ]]; then make -j8; fi
  - if [[ "$QF_ARCH" == "x86" ]]; then make -j8; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Release -target ALL_BUILD; fi
  - cd build
  - echo "${TRAVIS_COMMIT}" >commit.txt
  - echo "671610" >steam_appid.txt
  - if [[ "$QF_ARCH" == "OSX" ]]; then cd Release && tar -czvf ../../tmp.tar.gz *.app && cd ..; fi
  - if [[ "$QF_ARCH" != "OSX" ]]; then tar -czvf ../tmp.tar.gz * --exclude *.a --exclude base*/*.a libs/*.a; fi
  - cd ..
  - mv tmp.tar.gz ${QF_ARCH}-Release.tar.gz
  - curl -F "file=@${QF_ARCH}-Release.tar.gz" https://file.io
